#!/usr/bin/env python3
"""Generate data/pages.toml (spec §4): printed page ↔ scan page ↔ running head ↔ web anchor.

Printed pages come from the `{{< pg N >}}` markers in content/; scan numbers and running heads
from the OCR dump (tools/extract_pages.py). Image files are filled in once the scans exist.

    python3 tools/build_pages.py > data/pages.toml
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_pages import OFFSETS, SRC, pages, split_page  # noqa: E402
from validate import content_files, split_front_matter  # noqa: E402

heads = {}
for scan, lines in pages(SRC.read_text(encoding="utf-8")):
    if scan in OFFSETS:
        head, printed, _, _ = split_page(lines)
        printed = printed or scan - OFFSETS[scan]
        heads[printed] = (scan, head)

print("# Generated by tools/build_pages.py from content/ page markers and the OCR running heads.")
print("# Do not edit by hand. `image` is empty until the 400 dpi scans are added (spec §2).\n")
for f in content_files():
    fm, body, _ = split_front_matter(f.read_text(encoding="utf-8"), f)
    for m in re.finditer(r"\{\{<\s*pg\s+(\d+)\s*>\}\}", body):
        p = int(m.group(1))
        scan, head = heads.get(p, (None, []))
        # Right-hand pages: "[चैत्रमासः] <topic>", the topic sometimes on the next line.
        joined = " ".join(h.lstrip("?") for h in head)
        m2 = re.search(r"\[[^\]]+\]\s*([^\s।]+)", joined)
        rh = m2.group(1) if m2 else ""
        print(f"[p{p}]")
        print(f"printed = {p}")
        print(f"scan = {scan if scan else 0}")
        print(f'running_head = "{rh}"')
        print(f'topic = "{fm["id"]}"')
        print(f'url = "/{fm["didhiti"]}/{fm["section"]}/{fm.get("slug") or f.stem}/#p{p}"')
        print('image = ""\n')
