#!/usr/bin/env python3
"""Write a proof-reading checklist for one section: every correction and every `[?]`, by printed page.

Pass 1 readers work through it with the page images open (spec §5 step 5). Regenerate after edits.

    python3 tools/checklist.py caitra-krtyam > docs/proofreading/caitra-krtyam.md
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import ROOT, content_files, split_front_matter  # noqa: E402

TOKEN = re.compile(r'\{\{<\s*pg\s+(\d+)\s*>\}\}|\{\{<\s*corr ocr="([^"]*)"\s*>\}\}(.*?)\{\{<\s*/corr\s*>\}\}(\s*\[\?\])?|\[\?\]')
STRIP = re.compile(r"\{\{<[^>]*>\}\}")


def plain(s):
    """Text as a reader sees it: 1931 footnotes in parentheses, markup and paragraph IDs dropped."""
    s = re.sub(r"\{\{<\s*fn\s*>\}\}", " (fn: ", s)
    s = re.sub(r"\{\{<\s*/fn\s*>\}\}", ") ", s)
    s = re.sub(r"\{#p[\d.]+\}", " ", STRIP.sub("", s))
    return re.sub(r"\s+", " ", s)


def context(text, start, end, width=28):
    left = plain(text[max(0, start - 200):start])[-width:]
    right = plain(text[end:end + 200])[:width]
    return left.replace("|", "\\|"), right.replace("|", "\\|")


def main(section):
    offset = None
    rows = {}
    page = None
    for f in content_files():
        if f.parent.name != section:
            continue
        fm, body, _ = split_front_matter(f.read_text(encoding="utf-8"), f)
        offset = fm["scan_pages"][0] - fm["pages"][0]
        page = page or fm["pages"][0]
        for m in TOKEN.finditer(body):
            if m.group(1):
                page = int(m.group(1))
                continue
            l, r = context(body, m.start(), m.end())
            if m.group(2) is not None:
                ours, flag = STRIP.sub("", m.group(3)), "**[?]** " if m.group(4) else ""
                rows.setdefault(page, []).append(f"| {flag}{m.group(2) or '*(nothing)*'} | {ours} | …{l}⟨{ours}⟩{r}… | ☐ |")
            else:
                rows.setdefault(page, []).append(f"| **[?]** | – | …{l}⟨[?]⟩{r}… | ☐ |")
    print(f"# Proof-reading checklist: {section}\n")
    print("Generated by `tools/checklist.py` from `content/`; do not edit this file. Print it or copy it,")
    print("check each row against the page image, and fix `content/` in a pull request where a row is wrong.")
    print("`[?]` rows are readings nobody could settle from the OCR alone.\n")
    total = sum(len(v) for v in rows.values())
    flagged = sum(1 for v in rows.values() for r in v if r.startswith("| **[?]**"))
    print(f"{total} items on {len(rows)} pages, {flagged} flagged `[?]`.\n")
    for p in sorted(rows):
        print(f"## p.{p} (scan {p + offset:03d})\n")
        print("| OCR read | we print | context | ok |\n|---|---|---|---|")
        print("\n".join(rows[p]) + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "caitra-krtyam")
